/**
 * A CSS class name or a space-delimited string containing multiple class names.
 * Typically used to apply styles generated by a styling solution (e.g., CSS Modules, Tailwind CSS, Panda CSS).
 *
 * @remarks
 * An empty string or `""` is a valid value and will produce no additional styling.
 *
 * @example
 * ```ts
 * const baseStyle: RecipeStyle = "btn btn-primary";
 * const variantStyle: RecipeStyle = "bg-blue-500 hover:bg-blue-600";
 * ```
 */
export type RecipeStyle = string;

/**
 * A valid value that a variant option can hold.
 * Variants can be toggled using strings (e.g., `"sm"`), boolean flags (e.g., `true`), or numeric scales (e.g., `1`).
 */
export type RecipeVariantValue = string | boolean | number;

/**
 * A mapping of variant option names to their corresponding CSS class strings.
 * Each key represents a specific option for a variant group (e.g., `size` → `"sm"`), and the value defines the styles for that option.
 *
 * @example
 * ```ts
 * const colorVariants: RecipeVariant = {
 *   brand: "bg-brand text-white",
 *   destructive: "bg-red-500 text-white",
 *   outline: "border-2 border-current bg-transparent",
 * };
 * ```
 */
export type RecipeVariant = Record<string, RecipeStyle>;

/**
 * Defines a compound variant: a set of conditions (matching multiple variant keys)
 * that, when satisfied simultaneously, produce a specific CSS class name.
 *
 * This is useful when you need to apply styles only for specific combinations of variant values
 * (e.g., `variant="solid"` AND `color="brand"`).
 *
 * @property conditions - An object specifying the exact variant values required.
 * All specified key-value pairs must match the component's current props for the style to be applied.
 * @property className - The style to apply when all conditions are met.
 *
 * @example
 * ```ts
 * const compound: RecipeCompoundVariant = {
 *   conditions: { variant: "solid", color: "brand" },
 *   className: "shadow-lg bg-brand-dark",
 * };
 * ```
 */
export interface RecipeCompoundVariant {
  conditions: Record<string, RecipeVariantValue>;
  className: RecipeStyle;
}

/**
 * Defines a complete styling recipe for a single component.
 *
 * This pattern is inspired by libraries like `cva` (Class Variance Authority) and
 * provides a structured, type-safe way to manage component styles.
 *
 * The final `className` applied to the component is resolved in this order:
 * 1. `base` (always applied)
 * 2. All classes from matched `variants` (based on component props)
 * 3. All `className` values from matched `compoundVariants` (applied in array order)
 *
 * @example
 * ```ts
 * const buttonRecipe: RecipeDefinition = {
 *   base: "inline-flex items-center justify-center rounded font-medium transition-colors",
 *   variants: {
 *     variant: {
 *       solid: "bg-brand text-white hover:bg-brand-dark",
 *       outline: "border-2 border-brand text-brand hover:bg-brand/10",
 *       ghost: "text-brand hover:bg-brand/10",
 *     },
 *     size: {
 *       sm: "px-3 py-1 text-sm",
 *       md: "px-4 py-2 text-base",
 *       lg: "px-6 py-3 text-lg",
 *     },
 *   },
 *   defaultVariants: {
 *     variant: "solid",
 *     size: "md",
 *   },
 *   compoundVariants: [
 *     {
 *       conditions: { variant: "solid", size: "lg" },
 *       className: "shadow-lg",
 *     },
 *   ],
 * };
 * ```
 */
export interface RecipeDefinition {
  /**
   * Base CSS classes that are applied to every instance of the component.
   * These are combined with the classes from matched variants and compound variants.
   *
   * @example
   * ```ts
   * base: "flex items-center gap-2"
   * ```
   */
  base?: RecipeStyle;

  /**
   * A collection of variant groups.
   * Each key defines a variant prop name (e.g., `size`, `color`) that the component accepts.
   * The value is a map of possible option values → the CSS classes to apply for that option.
   *
   * @example
   * ```ts
   * variants: {
   *   size: {
   *     sm: "text-sm px-3 py-1",
   *     md: "text-base px-4 py-2",
   *   },
   *   color: {
   *     brand: "bg-brand text-white",
   *     destructive: "bg-red-500 text-white",
   *   },
   * }
   * ```
   */
  variants?: Record<string, RecipeVariant>;

  /**
   * The default variant values to use when no explicit prop is provided for a given variant key.
   *
   * @remarks
   * Supports string, boolean, and numeric values. If a variant key is omitted from this object,
   * and no prop is passed, the variant will not be applied.
   *
   * @example
   * ```ts
   * defaultVariants: {
   *   size: "md",
   *   rounded: false,
   * }
   * ```
   */
  defaultVariants?: Record<string, RecipeVariantValue>;

  /**
   * Conditional styles that are applied when multiple variant conditions are met.
   * Compound variants are evaluated against the final resolved props (including defaults).
   * Their `className` values are appended to the base and matching variant classes.
   *
   * @example
   * ```ts
   * compoundVariants: [
   *   {
   *     conditions: { variant: "solid", color: "brand" },
   *     className: "shadow-lg",
   *   },
   *   {
   *     conditions: { size: "lg", color: "destructive" },
   *     className: "uppercase",
   *   },
   * ]
   * ```
   */
  compoundVariants?: RecipeCompoundVariant[];
}

/**
 * The default set of recipes for the core UI components provided by the library.
 * These definitions serve as the baseline styling for fundamental building blocks.
 */
export type DefaultRecipeCollection = {
  Button: RecipeDefinition;
  FormControl: RecipeDefinition;
  Input: RecipeDefinition;
  Textarea: RecipeDefinition;
  MarkdownEditor: RecipeDefinition;
  Checkbox: RecipeDefinition;
  ButtonGroup: RecipeDefinition;
  Switch: RecipeDefinition;
  Container: RecipeDefinition;
  Link: RecipeDefinition;
};

/**
 * A record of user-defined component recipes, keyed by component name.
 * Use this to add custom components or override styling for application-specific needs.
 */
export type CustomRecipes = Record<string, RecipeDefinition>;

/**
 * The complete recipe configuration for the entire application.
 *
 * It merges the built-in default component recipes with any user‑defined custom recipes.
 * If a custom recipe shares a key with a default recipe, the custom definition takes precedence,
 * allowing you to fully replace the styling of core components.
 */
export type RecipeCollection = Partial<DefaultRecipeCollection> & CustomRecipes;
